Quantified/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'zscore.views.index'),
    url(r'^goal/add/$', 'zscore.views.goalAdd'),
    url(r'^priority/add/$', 'zscore.views.priorityAdd'),
    url(r'^goal/delete/$', 'zscore.views.goalDelete'),
    url(r'^priority/delete/$', 'zscore.views.priorityDelete'),
    url(r'^snapshot/add/$', 'zscore.views.snapshotAdd'),
    url(r'^snapshot/add/$', 'zscore.views.snapshotDelete'),


    # url(r'^$', 'Quantified.views.home', name='home'),
    # url(r'^Quantified/', include('Quantified.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

zscore/models.py
from django.db import models
import datetime, calendar

# Create your models here.

class Priority(models.Model):
    """ A priority class
    examples:
        Networking
        Fitness
        Programming Skills

     """
    # each priority has a name
    name = models.CharField(max_length=50)

    # each priority has a current value relative to other 
    # priorities
    currentWeight = models.FloatField('Current Weight')

    def __unicode__(self): 
        return self.name

class Goal(models.Model):
    """ a Goal class"""
    # each goal has an associated priority
    priority = models.ForeignKey(Priority)

    # the primitikve construction of a goal
    # think SMART
    verb = models.CharField(max_length=30)
    value = models.IntegerField('Goal Value')
    unit = models.CharField(max_length=30)
    FREQUENCY = (
        ('d', 'Day'),
        ('w', 'Week'),
        ('m', 'Month'),
        ('y', 'Year'),
    )
    frequency = models.CharField(max_length=10, choices=FREQUENCY)

    # every goal has a lifetime
    startDate = models.DateTimeField()
    endDate = models.DateTimeField()

    def getExpectedProgress(self):
        totalProgress = -1
        if self.frequency == 'Month':
            today = datetime.datetime.now()
            daysInMonth = float(calendar.monthrange(today.year,today.month)[1])
            return (float(today.day) / daysInMonth) * 100.0

        elif self.frequency == 'Week':
            today = datetime.datetime.now()
            weekday = today.weekday()+1
            return (weekday/7.0) * 100.0

        elif self.frequency == 'Day':
            today = datetime.datetime.now()
            firstHour = today.replace(minute=0, second=0, microsecond=0, hour=0)
            fiveAM = firstHour + datetime.timedelta(0.209)
            tenPM = firstHour + datetime.timedelta(0.921)

            if today < fiveAM:
                return 0.0
            elif today > tenPM:
                return 1.0
            else:
                return float((today.hour - fiveAM.hour)) / float((tenPM.hour - fiveAM.hour)) * self.value *100.0

    def getProgress(self):
        snaps = self.goalsnapshot_set.all()
        
        if len(snaps) == 0:
            return 0

        totalProgress = 0
        if self.frequency == 'Month':
            # get first day in the month
            today = datetime.datetime.now()
            firstDayOfMonth = today - datetime.timedelta(today.day-1)
            lastDayOfMonth = firstDayOfMonth + datetime.timedelta(calendar.monthrange(today.year,today.month)[1]-1)

            totalProgress = 0
            for snap in snaps:
                if snap.date >= firstDayOfMonth.date() and snap.date <= lastDayOfMonth.date():
                    totalProgress += snap.progress

        elif self.frequency == 'Week':

            mostRecentSunday = self.getNearestSunday()
            nextSunday = mostRecentSunday + datetime.timedelta(7)

            totalProgress = 0
            for snap in snaps:
                if snap.date < nextSunday.date() and snap.date >= mostRecentSunday.date(): #progress was made this week
                    totalProgress += snap.progress

        elif self.frequency == 'Day':
            today = datetime.datetime.now()
            firstHour = today.replace(minute=0, second=0, microsecond=0, hour=0)
            lastHour = firstHour + datetime.timedelta(1)

            for snap in snaps:
                if snap.date < lastHour.date() and snap.date >= firstHour.date():
                    totalProgress += snap.progress

        return (totalProgress/float(self.value))*100

    def getNearestSunday(self):
        today = datetime.datetime.now()
        weekday = today.weekday()
        lastSunday = today - datetime.timedelta(weekday + 1)
        return lastSunday

    def __unicode__(self): 
        return self.verb + " " + str(self.value) + " " + self.unit + " " + self.frequency


class GoalSnapshot(models.Model):
    """docstring for GoalSnapshot"""
    goal = models.ForeignKey(Goal)

    # the date of the snapshot
    date = models.DateField()

    # the progress made towards the goal for this snapshot
    progress = models.IntegerField('Progress')

    def __unicode__(self): 
        return str(self.progress) + " made on " + str(self.date)
        

class ZScoreSnapshot(models.Model):
    """docstring for ZScoreSnapshot"""
    value = models.IntegerField('ZScore')
    date = models.DateTimeField()

    def __unicode__(self): 
        return "ZScore from " + str(self.date) + ": " + str(self.value)
        

zscore/views.py
from django.template import Context, loader, RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.core.context_processors import csrf
from zscore.models import Priority, Goal, GoalSnapshot, ZScoreSnapshot

import datetime

from django.utils import timezone

def index(request):
    goals = Goal.objects.all()

    scores = ZScoreSnapshot.objects.all().order_by("-date")

    presentZScore = None
    if len(scores) == 0:
        presentZScore = 85
    else:
        presentZScore = scores[0].value
    
    dictionary = {
        'empty' : "nothin",
        'priorityList' : Priority.objects.all(),
        'zscore' : presentZScore,
    }
    c = Context(dictionary)
    c.update(csrf(request))
    return render_to_response('zscore/index_2.html', c, context_instance=RequestContext(request))


def goalAdd(request):
    post = request.POST
    priority = get_object_or_404(Priority, name=post["priority"])
    verb = post["verb"]
    value = float(post["value"])
    unit = post["unit"]
    frequency = post["frequency"]

    startDate = datetime.datetime.now()

    g = Goal(priority = priority, verb = verb, value = value, unit = unit, frequency = frequency, startDate = startDate, endDate=startDate)
    g.save()

    return redirect("/")

def goalDelete(request):
    post = request.POST
    goalId = int(post["id"])

    g = Goal.objects.all().filter(id=goalId).get()
    g.delete()

    return redirect("/")

def priorityAdd(request):
    post = request.POST
    weight = float(post["weight"])
    name = post["name"]

    p = Priority(name=name, currentWeight=weight)
    p.save()
    return redirect("/")

def priorityDelete(request):
    post = request.POST
    pId = int(post["id"])

    # delete the priority
    p = Priority.objects.all().filter(id=pId).get()
    p.delete()

    return redirect("/")

def snapshotAdd(request):
    # initial Values
    dailyCost = -1.0
    maxGain = 5.0


    # Save a new snapshot for this goal
    post = request.POST
    g = Goal.objects.all().filter(id=int(post["id"])).get()
    progress = int(post["progress"])
    newSnap = GoalSnapshot(goal=g, date=datetime.datetime.now(), progress=progress)
    newSnap.save()

    # get weight of priority
    priority = g.priority
    weight = float(priority.currentWeight)
    totWeights = sum([pIter.currentWeight for pIter in Priority.objects.all()])
    normalizedWeight = weight / totWeights

    # Get update amount
    # first, find percent progress made towards goal
    goalObjective = float(g.value)
    percentProgress = progress / goalObjective

    # Progress is based on percent towards maxGain
    Fk = int(percentProgress * maxGain)

    # weight based on priority
    Fk = Fk * normalizedWeight

    # get old Z Value
    scores = ZScoreSnapshot.objects.all().order_by("-date")
    
    Zk = None
    delta = None
    if len(scores) == 0:
        Zk = 85
        delta = 0
    else:
        ZScoreSnap = scores[0]
        ZScoreSnapDate = ZScoreSnap.date
        Zk = ZScoreSnap.value

        delta = abs((ZScoreSnapDate - timezone.now() + datetime.timedelta(1)).days)

    # Lose 'dailycost' per day
    # get number of days between updates
    totalLoss = delta * dailyCost
        
    # update ZScore
    Zk_1 = Zk + totalLoss + Fk

    # save the new snapshot
    ZSnap = ZScoreSnapshot(value=Zk_1, date=datetime.datetime.now())
    ZSnap.save()

    return redirect("/")

def snapshotDelete(request):
    post = request.POST
    g = Goal.objects.all().filter(id=int(post["id"])).get()

    p = int(post["progress"])

    p = -1*p

    newSnap = GoalSnapshot(goal=g, date=datetime.datetime.now(), progress=p)

    newSnap.save()
    return redirect("/")

    
    # dateComponents = request.POST['date'].split('/')
    # year = int(dateComponents[2])
    # month = int(dateComponents[0])
    # day = int(dateComponents[1])
    # workout_date = datetime.date(year, month, day)


    

templates/zscore/index.html
<!DOCTYPE html>
<html lang="en"> 
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Stylesheets -->
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/bootstrap3.css">

    <link href='http://fonts.googleapis.com/css?family=Quicksand:300|Lato:300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>




    <title> Test </title>

    <style type="text/css">

        /*Get rid of white margin upon resize. */
        @media (max-width: 767px){
            body {
                padding-right: 0px;
                padding-left: 0px;
            }
         }

        html, body {
            height: 100%;

        }

        .styled-container-white {
            color: #ffffff;
            font-family: 'Lato', sans-serif;
            font-weight: 300;
            font-size: 12pt;
        }

        .styled-container-dark {
            color: #000000;
            font-family: 'Lato', sans-serif;
            font-weight: 300;
            font-size: 12pt;
        }

        a:hover {
            text-decoration:none;
            color: #c0392b;
        }   

        .fullscreen {
            padding: 0 15px;
            width: 100%;
            height: 100%;

            position: relative;
        }

        .wideSection {
            padding: 0 15px;
            width: 100%;
            height: auto;
        }

        .title {
            font-family: 'Poiret One', sans-serif;
            font-weight: 400;
            color: #2ECC71;
            font-size: 35pt;
        }

        .page-footer {
            height: 30px;
            background-color: #ffffff;
            font-family: 'Open Sans', sans-serif;
            font-weight: 300;
            font-size: 12pt;
        }



    </style>

</head>


<body>
    <div class="fullscreen" >
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <h1 class="text-center">Hello Desmond, </h1>
                    <h1 class="text-center">Your Z Score for this week is</h1>

                </div>
            </div>
            <div class="row fullscreen-bottom">
                <div class="col-xs-12"></div>
            </div>
            <div class="col-xs-12">
                <h1 class="text-center">89</h1>                
            </div>
            <div class="col-xs-3">
                <div class="panel panel-default">
                    <div class="panel-heading">Network Cultivation</div>
                    <div class="panel-body">
                        <ul class="list-group">
                            <li class="list-group-item">Meet 3 people per week</li>
                            <li class="list-group-item">Send 1 email to old friend per week</li>
                            <li class="list-group-item">Go to 1 networking event per month</li>
                        </ul>
                    </div>
                </div>                
            </div>
            <div class="col-xs-3">
                <div class="panel panel-default">
                    <div class="panel-heading">Network Cultivation</div>
                    <div class="panel-body">
                        <ul class="list-group">
                            <li class="list-group-item">Meet 3 people per week</li>
                            <li class="list-group-item">Send 1 email to old friend per week</li>
                            <li class="list-group-item">Go to 1 networking event per month</li>
                        </ul>
                    </div>
                </div>                
            </div>
            <div class="col-xs-3">
                <div class="panel panel-default">
                    <div class="panel-heading">Network Cultivation</div>
                    <div class="panel-body">
                        <ul class="list-group">
                            <li class="list-group-item">Meet 3 people per week</li>
                            <li class="list-group-item">Send 1 email to old friend per week</li>
                            <li class="list-group-item">Go to 1 networking event per month</li>
                        </ul>
                    </div>
                </div>                
            </div>
            <div class="col-xs-3">
                <div class="panel panel-default">
                    <div class="panel-heading">Network Cultivation</div>
                    <div class="panel-body">
                        <ul class="list-group" >
                            <li class="list-group-item">Meet 3 people per week</li>
                            <li class="list-group-item">Send 1 email to old friend per week</li>
                            <li class="list-group-item">Go to 1 networking event per month</li>
                        </ul>
                    </div>
                </div>                
            </div>

        </div>
    </div>

<!-- Button trigger modal -->
<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

    <!-- Javascript -->
    <script type="text/javascript" src="https://code.jquery.com/jquery.js"></script>
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}js/bootstrap.js">

    <script type="text/javascript">
        $('#myModal').modal({
            keyboard: false
        })
    </script>

</body>




</html>

templates/zscore/index_2.html
<!DOCTYPE html>
<html>
  <head>
    <title>Bootstrap 101 Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Poiret+One|Quicksand:300|Lato:300' rel='stylesheet' type='text/css'>


    <style type="text/css">
        
        /*Get rid of white margin upon resize. */
        @media (max-width: 767px){
            body {
                padding-right: 0px;
                padding-left: 0px;
            }
         }

        html, body {
            height: 100%;
            font-family: 'Lato', sans-serif;
            /*font-weight: 300;*/
        }

        .huge {
            font-size: 40pt;
        }

        .score {
            font-size: 85pt;
            color: #55B95D;
        }

        .hoveredGoalGreen {
            background-color: #55B95D;
        }
        .hoveredGoalRed {
            background-color: #C0392B;
        }
        .hoveredGoalDark {
            background-color: #333739;
        }

        .goalbox {
            box-shadow: 0px 0px 6px 1px rgba(0, 0, 0, 0.3);
        }

        .test {
            width: 17px;
        }


    </style>

    
  </head>
  <body>
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h1 class="text-center huge">Hello Desmond, </h1>
                <h1 class="text-center huge">Your Z Score for this week is</h1>

            </div>
        </div>
        <div class="row fullscreen-bottom">
            <div class="col-xs-12"></div>
        </div>
        <div class="row">            
            <div class="col-xs-12">
                <h1 class="text-center score">{{ zscore }}</h1>                
            </div>
        </div>
        <div class="row" style="padding-top:20px; padding-bottom:45px;">
            <div class="col-xs-4 col-xs-offset-4">
                <!-- Button trigger modal -->
                <button class="btn btn-primary" data-toggle="modal" data-target="#priorityModal">
                    Add Priority
                </button>
                <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#goalModal">
                    Add Goal
                </button>
            </div>
        </div>

        <div class="row">
            {% for p in priorityList %}
            <div class="col-md-4 col-xs-12">
                <div class="panel panel-default goalbox" id="priority-{{ p.id }}">
                    <div class="panel-heading">{{ p.name }}<button type="button" value="{{ p.id }}"class="close pull-right deletePriority">&times;</button></div>
                    <div class="panel-body">
                        <ul class="list-group">
                            {% for goal in p.goal_set.all %}
                            <li class="list-group-item goalItem" id="goal-{{ goal.id }}">
                                <div class="row">
                                    <div class="col-xs-8">
                                        {{ goal.verb }} {{ goal.value }} {{ goal.unit }} per {{ goal.frequency }}
                                    </div>
                                <div class="col-xs-4">
                                    <button type="button" value="{{ goal.id }}"class="close pull-right deleteGoal">&times;</button>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-xs-12 col-md-7" style="padding-top:13px;">
                                        <div class="progress">
                                          <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: {{ goal.getProgress }}%">
                                          </div>
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-md-5" style="padding-top:8px;">
                                        <div class="input-group">
                                            <span class="input-group-btn">
                                                <button class="btn btn-default btn-sm minusSnap" type="button" value="{{ goal.id }}">&minus;</button>
                                            </span>
                                            <input type="text" class="form-control input-sm text-center" id="snapshotField-{{ goal.id }}" placeholder="1">
                                            <span class="input-group-btn">
                                                <button class="btn btn-default btn-sm plusSnap" type="button" value="{{ goal.id }}">&plus;</button>
                                            </span>
                                        </div>
                                    </div>
                                </div>

                            </li>

                            {% endfor %}
                        </ul>
                    </div>
                </div>                
            </div>
            {% endfor %}
        </div>
    </div>





<!-- Modal -->
<div class="modal fade" id="goalModal" tabindex="-1" role="dialog" aria-labelledby="goalModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="goalModalLabel">Add a new goal!</h4>
      </div>

<form class="form-horizontal" role="form" method="post" action="/goal/add/" id="goalForm">
    {% csrf_token %}
      <div class="modal-body">
        <span class="help-block">Break down your goals into the following format for easy tracking.</span>
            <div class="form-group">
                <label for="p-input" class="col-sm-offset-2 col-sm-2 control-label">Priority</label>
                <div class="col-sm-6">
                    <select id="p-input"class="form-control" name="priority">
                        {% for p in priorityList %}
                            <option>{{ p.name }}</option>
                        {% endfor %}
                    </select name="frequency">
                </div>
            </div>
          <div class="form-group">
            <label for="verb-input" class="col-sm-offset-2 col-sm-2 control-label">Verb</label>
            <div class="col-sm-6">
              <input type="text" class="form-control" id="verb-input" placeholder="Run" name="verb">
            </div>
          </div>
          <div class="form-group">
            <label for="value-input" class="col-sm-offset-2 col-sm-2 control-label">Value</label>
            <div class="col-sm-6">
                <input type="text" id="value-input" class="form-control" placeholder="10" name="value">
            </div>
          </div>
          <div class="form-group">
            <label for="unit-input" class="col-sm-offset-2 col-sm-2 control-label">Units</label>
            <div class="col-sm-6">
                <input type="text" id="unit-input" class="form-control" placeholder="miles per" name="unit">
            </div>
          </div>
            <div class="form-group">
            <label for="freq-input" class="col-sm-offset-2 col-sm-2 control-label">Frequency</label>
            <div class="col-sm-6">
                <select class="form-control" name="frequency">
                  <option>Day</option>
                  <option>Week</option>
                  <option>Month</option>
                  <option>Year</option>
                </select name="frequency">
            </div>
          </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Add   !</button>
      </div>
</form>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<!-- Modal -->
<div class="modal fade" id="priorityModal" tabindex="-1" role="dialog" aria-labelledby="priorityModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="priorityModalLabel">Add a new priority!</h4>
      </div>

<form class="form-horizontal" role="form" method="post" action="/priority/add/" id="priorityForm">
    {% csrf_token %}
      <div class="modal-body">
        <span class="help-block">Every priority has a name and a current weight relative to your other priorities. </span>
          <div class="form-group">
            <label for="name-input" class="col-sm-offset-2 col-sm-2 control-label">Name</label>
            <div class="col-sm-6">
              <input type="text" class="form-control" id="name-input" name="name" placeholder="Network Cultivation">
            </div>
          </div>
          <div class="form-group">
            <label for="value-input" class="col-sm-offset-2 col-sm-2 control-label">Weight</label>
            <div class="col-sm-6">
                <input type="text" id="value-input" class="form-control" name="weight" placeholder="87">
            </div>
          </div>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Add!</button>
      </div>
</form>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->




    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{{ STATIC_URL }}js/jquery_v1-10-2.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>

    <script type="text/javascript">



        function postIt(url, data){
            $('body').append($('<form/>', {
              id: 'jQueryPostItForm',
              method: 'POST',
              action: url
            }));
            
            $('#jQueryPostItForm').append($('<input/>', {
                type: 'hidden',
                name: 'id',
                value: data
            }));

            $('#jQueryPostItForm').append($('<input/>', {
                type: 'hidden',
                name: 'csrfmiddlewaretoken',
                value: "{{ csrf_token }}"
            }));

            $('#jQueryPostItForm').submit();
        }

        function postItSnapShot(url, data, progress){
            $('body').append($('<form/>', {
              id: 'jQueryPostItForm',
              method: 'POST',
              action: url
            }));
            
            $('#jQueryPostItForm').append($('<input/>', {
                type: 'hidden',
                name: 'id',
                value: data
            }));
            $('#jQueryPostItForm').append($('<input/>', {
                type: 'hidden',
                name: 'progress',
                value: progress
            }));


            $('#jQueryPostItForm').append($('<input/>', {
                type: 'hidden',
                name: 'csrfmiddlewaretoken',
                value: "{{ csrf_token }}"
            }));

            $('#jQueryPostItForm').submit();
        }

        $(".deleteGoal").click(function(){
            postIt("/goal/delete/", $(this).val());
        });
        $(".deletePriority").click(function(){
            postIt("/priority/delete/", $(this).val());
        });

        $(".plusSnap").click(function(){
            var id = $(this).val();
            if (!$("#snapshotField-"+id).val()) {
                postItSnapShot("/snapshot/add/", id, 1);
            }
            else {
                postItSnapShot("/snapshot/add/", id, $("#snapshotField-"+id).val());
            }
        });
        $(".minusSnap").click(function(){
            var id = $(this).val();
            if (!$("#snapshotField-"+id).val()) {
                postItSnapShot("/snapshot/add/", id, -1);
            }
            else {
                postItSnapShot("/snapshot/add/",id, -1*parseInt($("#snapshotField-"+id).val()));
            }
        });

        $( ".plusOneUnit" ).hover( function() {
            $( this ).parent().parent().parent().addClass( "hoveredGoalGreen" );
            }, function() {
            $( this ).parent().parent().parent().removeClass( "hoveredGoalGreen" );
        } );

        $( ".minusOneUnit" ).hover( function() {
            $( this ).parent().parent().parent().addClass( "hoveredGoalRed" );
            }, function() {
            $( this ).parent().parent().parent().removeClass( "hoveredGoalRed" );
        } );


    </script>
  </body>
</html>